version: '3'

services:
  catalog-db:
       image: gcr.io/vmwarecloudadvocacy/acmeshop-catalog-db:latest
       hostname: catalog-db
       environment:
        - MONGO_INITDB_ROOT_USERNAME=mongoadmin
        - MONGO_INITDB_ROOT_PASSWORD=secret
        - MONGO_INITDB_DATABASE=acmefit
       cap_add:
        - CHOWN
        - SETGID
        - SETUID
  catalog:
        image: gcr.io/vmwarecloudadvocacy/acmeshop-catalog:1.2.1
        hostname: catalog
        restart: always
        ports:
          - '8082:8082'
        cap_add:
          - NET_BIND_SERVICE
        environment:
             - CATALOG_DB_USERNAME=mongoadmin
             - CATALOG_DB_PASSWORD=secret
             - CATALOG_DB_HOST=catalog-db
             - CATALOG_PORT=8082
             - CATALOG_DB_PORT=27017
             - CATALOG_VERSION=v1
             - USERS_HOST=user
             - USERS_PORT=8083
             - JAEGER_AGENT_HOST=jaeger
             - JAEGER_AGENT_PORT=6831
        depends_on:
             - catalog-db
  user-db:
        image: gcr.io/vmwarecloudadvocacy/acmeshop-user-db:latest
        hostname: user-db
        environment:
          - MONGO_INITDB_ROOT_USERNAME=mongoadmin
          - MONGO_INITDB_ROOT_PASSWORD=secret
          - MONGO_INITDB_DATABASE=acmefit
        cap_add:
          - CHOWN
          - SETGID
          - SETUID
        tmpfs:
          - /tmp:rw,noexec,nosuid
  user-redis-db:
      image: bitnami/redis
      hostname: user-redis-db
      restart: always
      environment:
        - REDIS_PASSWORD=secret
      ports:
        - '6379'
  user:
       image: gcr.io/vmwarecloudadvocacy/acmeshop-user:2.0.1
       hostname: user
       restart: always
       ports:
         - '8083:8083'
       cap_add:
           - NET_BIND_SERVICE
       environment:
           - USERS_DB_USERNAME=mongoadmin
           - USERS_DB_PASSWORD=secret
           - USERS_DB_HOST=user-db
           - USERS_DB_PORT=27017
           - USERS_PORT=8083
           - REDIS_DB_HOST=user-redis-db
           - REDIS_DB_PORT=6379
           - REDIS_DB_PASSWORD=secret
           - JAEGER_AGENT_HOST=jaeger
           - JAEGER_AGENT_PORT=6831
  redis-db:
      image: bitnami/redis
      hostname: redis-db
      restart: always
      environment:
          - REDIS_PASSWORD=secret
      ports:
          - '6379:6379'
  cart:
      image: gcr.io/vmwarecloudadvocacy/acmeshop-cart:1.3.1
      hostname: cart
      restart: always
      environment:
          - REDIS_HOST=redis-db
          - REDIS_PORT=6379
          - REDIS_PASSWORD=secret
          - CART_PORT=5000
          - AUTH_MODE=1
          - USER_HOST=user
          - USER_PORT=8083
          - JAEGER_AGENT_HOST=jaeger
          - JAEGER_AGENT_PORT=6831
      ports:
          - '5000:5000'
      depends_on:
          - redis-db
  front-end:
       image: gcr.io/vmwarecloudadvocacy/acmeshop-front-end:2.2.0
       hostname: front-end
       restart: always
       ports:
          - '3000:3000'
       cap_add:
           - NET_BIND_SERVICE
       environment:
           - PORT=3000
           - USERS_HOST=user
           - CATALOG_HOST=catalog
           - CART_HOST=cart
           - ORDER_HOST=order
           - USERS_PORT=8083
           - CATALOG_PORT=8082
           - CART_PORT=5000
           - ORDER_PORT=6000
           - JAEGER_AGENT_HOST=jaeger
           - JAEGER_AGENT_PORT=6832
  jaeger:
      image: jaegertracing/all-in-one:1.11
      hostname: jaeger
      restart: always
      ports:
        - '14268:14268'
        - '16686:16686'
        - '5778:5778'
        - '6831-6832:6831-6832/udp'
        - '5775:5775/udp'
  postgres:
      image: postgres:12.1-alpine
      hostname: postgres
      restart: always
      ports:
        - '5432'
      environment:
        - POSTGRES_PASSWORD=password
        - POSTGRES_USER=postgres
        - POSTGRES_DB=postgres
  order:
      image: gcr.io/vmwarecloudadvocacy/order-postgres-tracing:3.0
      hostname: order
      restart: always
      ports:
        - '6000:6000'
      environment:
        - JAEGER_AGENT_HOST=jaeger
        - JAEGER_AGENT_PORT=6831
        - ORDER_DB_USERNAME=postgres
        - ORDER_AUTH_DB=postgres
        - ORDER_DB_PASSWORD=password
        - ORDER_DB_HOST=postgres
        - ORDER_DB_PORT=5432
        - ORDER_PORT=6000
        - PAYMENT_PORT=9000
        - PAYMENT_HOST=payment
        - AUTH_MODE=1
        - USER_PORT=8083
        - USER_HOST=user
      depends_on:
        - postgres
  payment:
       image: gcr.io/vmwarecloudadvocacy/acmeshop-payment:4.6
       hostname: payment
       restart: always
       ports:
         - '9000'
       environment:
         - JAEGER_AGENT_HOST=jaeger
         - JAEGER_AGENT_PORT=6832
         - PAYMENT_PORT=9000
         - USERS_HOST=user
         - USERS_PORT=8083
