apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: search-proc.default.tap.20231205011658.0.0
spec:
  refName: search-proc.default.tap
  version: 20231205011658.0.0
  releaseNotes: |
    Release v20231205011658.0.0 of package search-proc.default.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: projects.registry.vmware.com/tanzu_application_platform/supply-chain/search-proc-workloads-bundle@sha256:ef00d0830c71b21c6d17ba07550f493d238d0a2cbbdb9d598a31ea4b5a8a26c8
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          title: Workload name
          type: string
          default: ""
        replicas:
          title: Replicas
          type: integer
          default: 1
        port:
          title: Port
          type: integer
          default: 8080
        hostname:
          title: Hostname
          type: string
          default: ""
        cluster_issuer:
          title: Cluster Issuer
          type: string
          default: tap-ingress-selfsigned
        http_route:
          type: object
          additionalProperties: false
          nullable: true
          properties:
            gateways:
              type: array
              items:
                type: object
                additionalProperties: false
                properties:
                  protocol:
                    type: string
                    default: ""
                  name:
                    type: string
                    default: ""
              default:
              - protocol: https
                name: default-gateway