apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  creationTimestamp: null
  name: where-for-dinner-availability
spec:
  packageRef:
    refName: where-for-dinner-availability.apps.local
    versionSelection:
      constraints: 20240502.0.29860000
  serviceAccountName: carvel-package-installer
  values:
  - secretRef:
      name: where-for-dinner-availability-values
status:
  conditions: null
  friendlyDescription: ""
  observedGeneration: 0
