apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: hungryman
  namespace: workloads
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: hungryman
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/vmware-tanzu/application-accelerator-samples
      ref:
        branch: main
    subPath: hungryman/hungryman-api-gateway