#@ load("@ytt:data", "data")

#@ def buildFunctionDefinition():
#@ definitions = ""
#@ if data.values.applicationRole == "source":
#@ definitions = "supply" + data.values.objectModelClassName 
#@ end
#@ if data.values.applicationRole == "processor":
#@ if definitions != "":
#@    definitions = definitions + ":"
#@ end
#@ definitions = definitions + "process" + data.values.objectModelClassName 
#@ end
#@ if data.values.applicationRole == "sink":
#@ if definitions != "":
#@    definitions = definitions + ":"
#@ end
#@ definitions = definitions + "store" + data.values.objectModelClassName 
#@ end
#@ return definitions
#@ end

---
server.port: 0

spring:
  application:
    name: #@ data.values.projectName

  cloud: 
    function: 
      definition: #@ buildFunctionDefinition()
    stream:
      defaultBinder: rabbit
      function:
        bindings:
#@ if data.values.applicationRole == "sink":
          storeFoo-in-0: input
#@ end
#@ if data.values.applicationRole == "processor":
          processFoo-in-0: input
          processFoo-out-0: output
#@ end
#@ if data.values.applicationRole == "source":   
          supplyFoo-out-0: output
#@ end
      bindings:
#@ if data.values.applicationRole == "sink":
        input: 
          destination: #@ data.values.resultChannel
          group: #@ data.values.resultChannelGroup
          consumer: 
            maxAttempts: 4
            backOffInitialInterval: 15000
            backOffMaxInterval: 60000 
#@ end
#@ if data.values.applicationRole == "processor":
        input: 
          destination: #@ data.values.sourceChannel
          group: #@ data.values.sourceChannelGroup
          consumer: 
            maxAttempts: 4
            backOffInitialInterval: 15000
            backOffMaxInterval: 60000          
        output: 
          destination: #@ data.values.resultChannel
#@ end 
#@ if data.values.applicationRole == "source":       
        output: 
          destination: #@ data.values.sourceChannel
#@ end

---
spring:
  config:
    activate:
      on-cloud-platform: kubernetes

server.port: 8080