apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGatewayRouteConfig
metadata:
  name: catalog-route-config
spec:
  service:
    name: catalog
    port: 8082
  routes:
    - predicates:
        - Path=/products
        - Method=GET
      filters:
        - StripPrefix=0
      tags:
        - catalog
    - predicates:
        - Path=/products/{id}
        - Method=GET
      filters:
        - StripPrefix=0
      tags:
        - catalog
    - predicates:
        - Path=/catalogliveness
        - Method=GET
      filters:
        - StripPrefix=0
        - SetPath=/liveness
      tags:
        - catalog
    - predicates:
        - Path=/static/images/{id}
        - Method=GET
      filters:
        - StripPrefix=0
      tags:
        - catalog
---
apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGatewayMapping
metadata:
  name: catalog-routes
spec:
  gatewayRef:
    name: gateway
  routeConfigRef:
    name: catalog-route-config
