apiVersion: v1
kind: Service
metadata:
  name: order
  labels:
    app: acmefit
    service: order
spec:
  ports:
    - name: http-order
      protocol: TCP
      port: 6000
  selector:
    app: acmefit
    service: order
---
apiVersion: apps/v1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: order
  labels:
    app: acmefit
    service: order
spec:
  selector:
    matchLabels:
      app: acmefit
      service: order
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: acmefit
        service: order
    spec:
      volumes:
      - name: acmefit-order-data
        emptyDir: {}
      containers:
      - image: springcloudservices/fitness-order:wavefront
        # orderpostgres:latest
        name: order
        env:
        - name: ORDER_DB_HOST
          value: order-postgres
        - name: ORDER_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: order-postgres-pass
              key: password
        - name: ORDER_DB_PORT
          value: '5432'
        - name: AUTH_MODE
          value: '1'
        - name: ORDER_DB_USERNAME
          value: pgbench
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: order-postgres-pass
              key: password
        - name: ORDER_AUTH_DB
          value: postgres
        - name: ORDER_PORT
          value: '6000'
        - name: PAYMENT_PORT
          value: '9000'
        - name: PAYMENT_HOST
          value: 'payment'
        - name: USER_HOST
          value: 'gateway'
        - name: USER_PORT
          value: '80'
        - name: TRACER_HOST
          value: 'wavefront-proxy'
        - name: TRACER_PORT
          value: '9411'
        ports:
        - containerPort: 6000
          name: order
        volumeMounts:
        - mountPath: "/data"
          name: "acmefit-order-data"
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
