version: '2'

services:
    cart:
       image: acmeshop-cart:latest
       hostname: cart
       restart: always
       ports:
          - '5000:5000'
       cap_drop:
           - all
       cap_add:
           - NET_BIND_SERVICE
       read_only: true
    reddb:
       image: redis:5.0.3-alpine
       hostname: reddb
       restart: always
       cap_drop:
           - all
       cap_add:
           - NET_BIND_SERVICE
       ports:
           - '6379:6379'
