FROM ubuntu:latest
MAINTAINER Bill Shetti "billshetti@gmail.com"
RUN apt-get update -y && \
    apt-get install -y python3-pip && \
    pip3 install --upgrade setuptools pip && \

COPY ./requirements.txt /app/requirements.txt
WORKDIR /app
RUN pip3 install -r requirements.txt
COPY . /app
EXPOSE 80
EXPOSE 5000
ENTRYPOINT ["python"]
CMD ["cart.py"]
