#@ load("@ytt:data", "data")
---
apiVersion: sso.apps.tanzu.vmware.com/v1alpha1
kind: ClientRegistration
metadata:
  name: #@ data.values.workload_name
  namespace: #@ data.values.namespace
spec:
  authServerSelector:
    matchLabels: #@ data.values.authserver_label
  clientAuthenticationMethod: client_secret_basic
  authorizationGrantTypes:
    - authorization_code
  redirectURIs:
    - #@ "https://{}.{}.{}/login/oauth2/code/{}".format(data.values.workload_name, data.values.namespace, data.values.domain, data.values.workload_name)
    - #@ "http://{}.{}.{}/login/oauth2/code/{}".format(data.values.workload_name, data.values.namespace, data.values.domain, data.values.workload_name)
  scopes:
    - name: openid
