apiVersion: accelerator.apps.tanzu.vmware.com/v1alpha1
kind: Accelerator
metadata:
  name: java-server-side-ui
  namespace: accelerator-system
spec:
  git:
    url: https://github.com/vmware-tanzu/application-accelerator-samples.git
    ref:
      branch: main
    subPath: java-server-side-ui
