apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hungryman-api-gateway
  annotations:
    "backstage.io/kubernetes-label-selector": "app.kubernetes.io/part-of=hungryman"
spec:
  type: service
  lifecycle: experimental
  owner: hungryman-team
  system: hungryman
  dependsOn: 
    - component:hungryman-ui
