#@ load("@ytt:data", "data")

---
apiVersion: with.sql.tanzu.vmware.com/v1
kind: MySQL
metadata:
  name: #@ data.values.dbName
  namespace: #@ data.values.serviceNamespace
  labels:
    services.apps.tanzu.vmware.com/class: mysql-where-for-dinner  
spec:
  databasePodConfig:
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchExpressions:
                  - key: "app.kubernetes.io/component"
                    operator: In
                    values:
                      - database
                  - key: "app.kubernetes.io/instance"
                    operator: In
                    values:
                      - where-for-dinner
    tolerations:
    - key: node.kubernetes.io/disk-pressure
      operator: "Exists"
      effect: "NoExecute"
      tolerationSeconds: 3600
  proxyPodConfig:
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchExpressions:
                  - key: "app.kubernetes.io/component"
                    operator: In
                    values:
                      - proxy
                  - key: "app.kubernetes.io/instance"
                    operator: In
                    values:
                      - where-for-dinner
    tolerations:
    - key: node.kubernetes.io/memory-pressure
      operator: "Exists"
      effect: "NoExecute"
      tolerationSeconds: 3600
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mysql-app-operator-reader
  labels:
    servicebinding.io/controller: "true"
rules:
- apiGroups: ["with.sql.tanzu.vmware.com"]
  resources: ["mysqls"]
  verbs: ["get", "list", "watch"]
---
apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ClusterInstanceClass
metadata:
  name: mysql-where-for-dinner
spec:
  description:
    short: Where For Dinner MySQL DB Instances
  pool:
    group: with.sql.tanzu.vmware.com
    kind: MySQL  
    labelSelector:
      matchLabels:
        services.apps.tanzu.vmware.com/class: mysql-where-for-dinner  
