version: "3.9"

volumes:
  mysql-volume:
    driver: local

services:
  mysql:
    image: mysql:8
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=development
      - MYSQL_USER=local_test
      - MYSQL_PASSWORD=password
    ports:
      - '3306:3306'
    volumes:
      -   mysql-volume:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - '8081:8080'
