management:
  endpoints:
    web:
      exposure:
        include: info,health

spring:
  config:
    activate:
      on-profile: tap
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_URI}