
---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xrabbitmqclusters.wherefordinner.messaging.example.org
spec:
  connectionSecretKeys:
  - host
  - password
  - port
  - provider
  - type
  - username
  group: wherefordinner.messaging.example.org
  names:
    kind: XRabbitmqCluster
    plural: xrabbitmqclusters
  versions:
  - name: v1alpha1
    referenceable: true
    schema:
      openAPIV3Schema:
        properties:
          spec:
            description: The OpenAPIV3Schema of this Composite Resource Definition.
            properties:
              replicas:
                description: The desired number of replicas forming the cluster
                type: integer
              storageGB:
                description: The desired storage capacity of a single replica, in GB.
                type: integer
              serviceNamespace:
                description: The namespace that the service will be deployed to.
                type: string                
            type: object
        type: object
    served: true
---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xrabbitmqclusters.wherefordinner.messaging.example.org
spec:
  compositeTypeRef:
    apiVersion: wherefordinner.messaging.example.org/v1alpha1
    kind: XRabbitmqCluster
  publishConnectionDetailsWithStoreConfigRef:
    name: default
  resources:
  - base:
      apiVersion: kubernetes.crossplane.io/v1alpha1
      kind: Object
      spec:
        forProvider:
          manifest:
            apiVersion: rabbitmq.com/v1beta1
            kind: RabbitmqCluster
            metadata:
              namespace: service-instances
              annotations:
                rabbitmq.com/topology-allowed-namespaces: '*'
            spec:
              replicas: 1
              resources:
                requests:
                  cpu: 200m
                limits:
                  cpu: 200m
        connectionDetails:
        - apiVersion: v1
          kind: Secret
          fieldPath: data.provider
          toConnectionSecretKey: provider
        - apiVersion: v1
          kind: Secret
          fieldPath: data.type
          toConnectionSecretKey: type
        - apiVersion: v1
          kind: Secret
          fieldPath: data.host
          toConnectionSecretKey: host
        - apiVersion: v1
          kind: Secret
          fieldPath: data.port
          toConnectionSecretKey: port
        - apiVersion: v1
          kind: Secret
          fieldPath: data.username
          toConnectionSecretKey: username
        - apiVersion: v1
          kind: Secret
          fieldPath: data.password
          toConnectionSecretKey: password
        writeConnectionSecretToRef:
          namespace: default                    
    patches:
      - fromFieldPath: spec.serviceNamespace
        toFieldPath: spec.writeConnectionSecretToRef.namespace    
        type: FromCompositeFieldPath          
      - fromFieldPath: metadata.uid
        toFieldPath: spec.writeConnectionSecretToRef.name
        transforms:
        - string:
            fmt: '%s-rmq'
            type: Format
          type: string
        type: FromCompositeFieldPath       
      - fromFieldPath: spec.serviceNamespace
        toFieldPath: spec.forProvider.manifest.metadata.namespace
        type: FromCompositeFieldPath       
      - fromFieldPath: metadata.name
        toFieldPath: spec.forProvider.manifest.metadata.name
        type: FromCompositeFieldPath
      - fromFieldPath: spec.replicas
        toFieldPath: spec.forProvider.manifest.spec.replicas
        type: FromCompositeFieldPath   
      - fromFieldPath: metadata.name
        toFieldPath: spec.connectionDetails[0].name
        transforms:
        - string:
            fmt: '%s-default-user'
            type: Format
          type: string
        type: FromCompositeFieldPath     
      - fromFieldPath: metadata.name
        toFieldPath: spec.connectionDetails[1].name
        transforms:
        - string:
            fmt: '%s-default-user'
            type: Format
          type: string
        type: FromCompositeFieldPath   
      - fromFieldPath: metadata.name
        toFieldPath: spec.connectionDetails[2].name
        transforms:
        - string:
            fmt: '%s-default-user'
            type: Format
          type: string
        type: FromCompositeFieldPath 
      - fromFieldPath: metadata.name
        toFieldPath: spec.connectionDetails[3].name
        transforms:
        - string:
            fmt: '%s-default-user'
            type: Format
          type: string
        type: FromCompositeFieldPath 
      - fromFieldPath: metadata.name
        toFieldPath: spec.connectionDetails[4].name
        transforms:
        - string:
            fmt: '%s-default-user'
            type: Format
          type: string
        type: FromCompositeFieldPath 
      - fromFieldPath: metadata.name
        toFieldPath: spec.connectionDetails[5].name
        transforms:
        - string:
            fmt: '%s-default-user'
            type: Format
          type: string
        type: FromCompositeFieldPath 
      - fromFieldPath: spec.serviceNamespace
        toFieldPath: spec.connectionDetails[0].namespace
        type: FromCompositeFieldPath    
      - fromFieldPath: spec.serviceNamespace
        toFieldPath: spec.connectionDetails[1].namespace
        type: FromCompositeFieldPath    
      - fromFieldPath: spec.serviceNamespace
        toFieldPath: spec.connectionDetails[2].namespace
        type: FromCompositeFieldPath    
      - fromFieldPath: spec.serviceNamespace
        toFieldPath: spec.connectionDetails[3].namespace
        type: FromCompositeFieldPath    
      - fromFieldPath: spec.serviceNamespace
        toFieldPath: spec.connectionDetails[4].namespace
        type: FromCompositeFieldPath    
      - fromFieldPath: spec.serviceNamespace
        toFieldPath: spec.connectionDetails[5].namespace
        type: FromCompositeFieldPath           
    connectionDetails:
    - fromConnectionSecretKey: type
      name: type
    - fromConnectionSecretKey: provider
      name: provider
    - fromConnectionSecretKey: password     
      name: password 
    - fromConnectionSecretKey: username
      name: username      
    - fromConnectionSecretKey: host
      name: host       
    - fromConnectionSecretKey: port 
      name: port  
---
apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ClusterInstanceClass
metadata:
  name: msgbroker-crossplane-where-for-dinner
spec:
  description:
    short: RabbitMQ
  provisioner:
    crossplane:
      compositeResourceDefinition: xrabbitmqclusters.wherefordinner.messaging.example.org
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
 name: crossplane-kubernetes-provider-rmq-read-writer
 labels:
   services.tanzu.vmware.com/aggregate-to-provider-kubernetes: "true"
rules:
- apiGroups: ["rabbitmq.com"]
  resources: ["rabbitmqclusters"]
  verbs: ["*"]