
---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xrabbitmqclusters.wherefordinner.messaging.example.org
spec:
  connectionSecretKeys:
  - host
  - password
  - port
  - provider
  - type
  - username
  group: wherefordinner.messaging.example.org
  names:
    kind: XRabbitmqCluster
    plural: xrabbitmqclusters
  versions:
  - name: v1alpha1
    referenceable: true
    schema:
      openAPIV3Schema:
        properties:
          spec:
            description: The OpenAPIV3Schema of this Composite Resource Definition.
            properties:
              replicas:
                description: The desired number of replicas forming the cluster
                type: integer
              storageGB:
                description: The desired storage capacity of a single replica, in GB.
                type: integer
              serviceNamespace:
                description: The namespace that the service will be deployed to.
                type: string                
            type: object
        type: object
    served: true
---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xrabbitmqclusters.wherefordinner.messaging.example.org
spec:
  compositeTypeRef:
    apiVersion: wherefordinner.messaging.example.org/v1alpha1
    kind: XRabbitmqCluster
  publishConnectionDetailsWithStoreConfigRef:
    name: default
  resources:
  - base:
      apiVersion: kubernetes.crossplane.io/v1alpha1
      kind: Object
      spec:
        forProvider:
          manifest:
            apiVersion: rabbitmq.com/v1beta1
            kind: RabbitmqCluster
            metadata:
              namespace: service-instances
              annotations:
                rabbitmq.com/topology-allowed-namespaces: '*'
            spec:
              replicas: 1
              resources:
                requests:
                  cpu: 200m
                limits:
                  cpu: 200m
    patches:
      - fromFieldPath: spec.serviceNamespace
        toFieldPath: spec.forProvider.manifest.metadata.namespace
        type: FromCompositeFieldPath       
      - fromFieldPath: metadata.name
        toFieldPath: spec.forProvider.manifest.metadata.name
        type: FromCompositeFieldPath
      - fromFieldPath: spec.replicas
        toFieldPath: spec.forProvider.manifest.spec.replicas
        type: FromCompositeFieldPath     
  - base:
      apiVersion: kubernetes.crossplane.io/v1alpha1
      kind: Object
      spec:
        forProvider:
          manifest:
            apiVersion: secretgen.carvel.dev/v1alpha1
            kind: SecretTemplate
            metadata:
              namespace: service-instances
            spec:
              inputResources:
              - name: creds
                ref:
                  apiVersion: v1
                  kind: Secret
              template:
                type: connection.crossplane.io/v1alpha1
                data:
                  provider: "$(.creds.data.provider)"
                  type: "$(.creds.data.type)"
                  host: "$(.creds.data.host)"
                  port: "$(.creds.data.port)"
                  username: "$(.creds.data.username)"
                  password: "$(.creds.data.password)"
    patches: 
      - fromFieldPath: spec.serviceNamespace
        toFieldPath: spec.forProvider.manifest.metadata.namespace    
      - fromFieldPath: metadata.name
        toFieldPath: spec.forProvider.manifest.spec.inputResources[0].ref.name
        transforms:
        - string:
            fmt: '%s-default-user'
            type: Format
          type: string
        type: FromCompositeFieldPath
      - fromFieldPath: spec.writeConnectionSecretToRef.name
        toFieldPath: spec.forProvider.manifest.metadata.name
        type: FromCompositeFieldPath
  - base:
      apiVersion: kubernetes.crossplane.io/v1alpha1
      kind: Object
      spec:
        forProvider:
          manifest:
            apiVersion: secretgen.carvel.dev/v1alpha1
            kind: SecretExport
            metadata:
              namespace: service-instances
    patches:
      - fromFieldPath: spec.serviceNamespace
        toFieldPath: spec.forProvider.manifest.metadata.namespace    
      - fromFieldPath: spec.writeConnectionSecretToRef.name
        toFieldPath: spec.forProvider.manifest.metadata.name
        type: FromCompositeFieldPath
      - fromFieldPath: spec.writeConnectionSecretToRef.namespace
        toFieldPath: spec.forProvider.manifest.spec.toNamespace
        type: FromCompositeFieldPath
  - base:
      apiVersion: kubernetes.crossplane.io/v1alpha1
      kind: Object
      spec:
        forProvider:
          manifest:
            apiVersion: secretgen.carvel.dev/v1alpha1
            kind: SecretImport
            spec:
              fromNamespace: service-instances
    patches:
      - fromFieldPath: spec.serviceNamespace
        toFieldPath: spec.forProvider.manifest.metadata.namespace    
      - fromFieldPath: spec.writeConnectionSecretToRef.name
        toFieldPath: spec.forProvider.manifest.metadata.name
        type: FromCompositeFieldPath
      - fromFieldPath: spec.writeConnectionSecretToRef.namespace
        toFieldPath: spec.forProvider.manifest.metadata.namespace
        type: FromCompositeFieldPath
---
apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ClusterInstanceClass
metadata:
  name: msgbroker-crossplane-where-for-dinner
spec:
  description:
    short: RabbitMQ
  provisioner:
    crossplane:
      compositeResourceDefinition: xrabbitmqclusters.wherefordinner.messaging.example.org
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
 name: crossplane-kubernetes-provider-rmq-read-writer
 labels:
   services.tanzu.vmware.com/aggregate-to-provider-kubernetes: "true"
rules:
- apiGroups: ["rabbitmq.com"]
  resources: ["rabbitmqclusters"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crossplane-kubernetes-secret-import-read-writer
  labels:
    services.tanzu.vmware.com/aggregate-to-provider-kubernetes: "true"
rules:
- apiGroups:
  - secretgen.carvel.dev
  resources:
  - secretimports
  verbs:
  - '*'
