#@ load("@ytt:data", "data")

#@ if data.values.dynamicCache == False:
---
apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ResourceClaimPolicy
metadata:
  name: where-for-dinner-bitnami-redis-cross-namespace
  namespace: #@ data.values.serviceNamespace
spec:
  consumingNamespaces:
  - '*'
  subject:
    group: ""
    kind: Secret
---
apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ClassClaim
metadata:
  name: #@ data.values.cacheName
  namespace: #@ data.values.workloadNamespace
spec:
  classRef:
    name: bitnami-redis-where-for-dinner
#@ else: 
---
apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ClassClaim
metadata:
  name: #@ data.values.cacheName
  namespace: #@ data.values.workloadNamespace
spec:
  classRef:
    name: #@ data.values.dynamicCacheClass
  parameters:
    replicas: 1    
    serviceNamespace: #@ data.values.serviceNamespace    
#@ end