#@ load("@ytt:data", "data")

---
apiVersion: tanzu.vmware.com/v1
kind: SpringCloudGatewayRouteConfig
metadata:
  name: ui-route-config
  namespace: #@ data.values.workloadNamespace
spec:
  openapi:
    generation:
      enabled: false
  routes:
  - predicates:
    - Path=/**
    - Method=GET
    order: 1000
    filters:
    - StripPrefix=0
    tags:
    - ui
#@ if data.values.enableSecurity == True:    
  - predicates:
    - Path=/diningsearch/**
    - Method=GET
    order: 2
    filters:
    - StripPrefix=0  
    ssoEnabled: true    
    tags:
    - ui-secure    
#@ end
  service:
    uri: #@ 'http://where-for-dinner-ui.' + data.values.workloadNamespace
---
apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGatewayMapping
metadata:
  name: ui-route-mapping
  namespace: #@ data.values.workloadNamespace
spec:
  gatewayRef:
    name: #@ data.values.gatewayName
  routeConfigRef:
    name: ui-route-config
