server:
  port: 8081
  # When running behind a reverse proxy, this stradedgy needs to be set to ensure
  # that OpenAPI endpoint returns the correct server URLs
  # https://springdoc.org/faq.html#_how_can_i_deploy_springdoc_openapi_ui_behind_a_reverse_proxy
  forward-headers-strategy: framework

hungryman:
  searchEvent:
    period: 120000
    
spring: 
  sql.init.mode: ALWAYS 

  cloud: 
    stream:
      poller:
        fixed-delay: ${hungryman.searchEvent.period} 
      function:
        definition: submittedSearches
      bindings: 
        submittedSearches-out-0: 
          destination: hungryman-search-criteria

springdoc:
  packages-to-scan: com.java.example.tanzu.hungryman.resources
  show-spring-cloud-functions: false
          
---

spring:
  config.activate.on-profile: mysql
  
  r2dbc: 
    #Default properties to work with MariaDB driver
    properties.sslMode: TRUST  
    properties.tlsVersion: TLSv1.2