apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: postal-code-search
  labels:
    apps.tanzu.vmware.com/workload-type: server
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    app.kubernetes.io/part-of: postal-code-search
spec:
  env:
  - name: spring_profiles_active
    value: oauth2   
  resources:     
    requests:         
      memory: "500M"
      cpu: "100m"
    limits:         
      memory: "750M"
      cpu: "1500m"         
  build:
    env:
      - name: BP_JVM_VERSION
        value: "21"      
  serviceClaims:
  - name: sso
    ref:
      apiVersion: services.apps.tanzu.vmware.com/v1alpha1
      kind: ClassClaim
      name: appsso-postal-codes 
  source:
    git:
      url: <https URL for your generated project's Git repository>
      ref:
        branch: main
    subPath: postal-code-search