apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: acme-order
  description: ACME Fitness Store  Order Service
  tags:
    - tanzu
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/part-of=acme-order'
spec:
  type: service
  lifecycle: production
  owner: default-team
  system: fitness-store
