apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: service-binding-mysql
  labels:
    servicebinding.io/controller: "true" 
rules:
  - apiGroups: ["with.sql.tanzu.vmware.com"]
    resources: ["mysql"]
    verbs: ["get", "list", "watch"]
