apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: postal-code-audit
  annotations:
    "backstage.io/kubernetes-label-selector": "app.kubernetes.io/part-of=postal-code-audit"
spec:
  type: service
  lifecycle: experimental
  owner: postal-code-team
  system: postal-code
  dependsOn: 
    - resource:postal-code-db
    - resource:postal-code-messaging
    - resource:postal-code-sso
    - resource:postal-code-gateway
