server.port: 8082

spring:
  application:
    name: audit

  flyway:
    baseline-on-migrate: true
    enabled: true 
    locations: classpath:db/migration/{vendor}
    out-of-order: false
    table: audit-schema-version
    validate-on-migrate: false
    
  cloud: 
    function:
      definition: processAuditEvent
    stream:
      defaultBinder: rabbit
      bindings: 
        processAuditEvent-in-0: 
          destination: postal-code-audit-events
          group: postal-code-audit-events-group
          consumer: 
            maxAttempts: 4
            backOffInitialInterval: 15000
            
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    
  r2dbc: 
    url: r2dbc:h2:mem:///testdb    
    username: sa

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${POSTAL_CODE_ISS_URL}

auidit:
  api:
    authorized-role: ROLE_SECURITY_OFFICER

---

spring:
  config.activate.on-profile: mysql
 
  r2dbc: 
    properties.sslMode: TRUST  
    properties.tlsVersion: TLSv1.2  
    