apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hungryman-availability
  annotations:
    "backstage.io/kubernetes-label-selector": "app.kubernetes.io/part-of=hungryman"
spec:
  type: service
  lifecycle: experimental
  owner: hungryman-team
  system: hungryman
  dependsOn: 
    - resource:hungryman-db
    - resource:hungryman-messaging
    - component:hungryman-search-proc
  providesApis:
    - hungryman-availability
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: hungryman-availability
  description: The Availability API
  tags:
    - api
    - tanzu
spec:
  type: openapi
  lifecycle: experimental
  owner: hungryman-team
  system: hungryman
  definition:
    $text: https://hungryman.perfect300rock.com/api/availability/v3/api-docs/
