server.port: 0

spring:
  application:
    name: streaming-app-template

  cloud: 
    function:
      definition: processFoo:storeFoo:supplyFoo 
    stream:
      defaultBinder: rabbit
      bindings: 
        storeFoo-in-0: 
          destination: foo-result
          group: foo-result-group
          consumer: 
            maxAttempts: 4
            backOffInitialInterval: 15000
            backOffMaxInterval: 60000 
        processFoo-in-0: 
          destination: foo-source
          group: foo-group
          consumer: 
            maxAttempts: 4
            backOffInitialInterval: 15000
            backOffMaxInterval: 60000             
        processFoo-out-0: 
          destination: foo-result
        supplyFoo-out-0: 
          destination: foo-source