apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: angular-test-pipeline
  labels:
    apps.tanzu.vmware.com/pipeline: test-angular
spec:
  params:
    - name: source-url
    - name: source-revision
  tasks:
    - name: test
      params:
        - name: source-url
          value: $(params.source-url)
        - name: source-revision
          value: $(params.source-revision)
      taskSpec:
        params:
          - name: source-url
          - name: source-revision
        steps:
          - name: angular-test-chrome-headless
            image: zenika/alpine-chrome:102-with-node-16
            script: |-
              cd `mktemp -d`
              wget -qO- $(params.source-url) | tar xvz -m

              npm install
              npm run test-headless
