apiVersion: sql.tanzu.vmware.com/v1
kind: Postgres
metadata:
  name: customer-profile-database
spec:
  memory: 800Mi
  cpu: "0.8"
  # storageClassName: standard
  storageSize: 2G
  pgConfig:
    dbname: customerprofiledatabase
    username: pgadmin
    appUser: pgappuser